### ISSUE TITLE
Angular Error: Too few bytes to read ASN.1 value.

### ISSUE THREAD

**Issue by farisshomali** [remdra/sign-pdf-lib#5]
My code :

      PDFViewerApplication.pdfDocument.getData().then(async pdfData => {

        http.get('assets/AccuSign.p12', {responseType: 'arraybuffer'}).subscribe(async data => {

        const settings: SignerSettings = {
          rangePlaceHolder: 9999, signatureComputer: <P12SignatureComputerSettings>{
            password: '1q2w3e',
            certificate: Buffer.from(data)
          }, signatureLength: 4096
        };

        const parameters: SignVisualParameters = {
          pageNumber: 1,
          rectangle: {
            left: 50,
            top: 641,
            right: 264,
            bottom: 711
          },
          texts: [{
            lines: [
              'Faris',
              'Shomali'
            ]
          }, {
            lines: [
              'Digitally signed by',
              'Faris Shomali',
              'Date: 2023.11.03',
              '20:28:46 +02\'00\''
            ]
          }
          ]
        };
        
        const pdfSigner = new PdfSigner(settings);
        const signedPdf = await pdfSigner.signVisualAsync(Buffer.from(pdfData), parameters);
      });

    })

![Screen Shot 2024-04-22 at 1 03 56 PM](https://github.com/remdra/sign-pdf-lib/assets/61110881/c6d24d7d-7b39-438f-a995-9ad174ce1d76)

**Comment by remdra** [comment]
Fixed in version 2.0.3.
Please pay attention that now there a 2 signers: digital and visual. Read the section 'Visual signer usage' from documentation.

PS: Reopen if you still have issues.

**Comment by farisshomali** [comment]
Reopening.

Version=> "sign-pdf-lib": "^2.0.3"

I really don't know what is wrong here!

Every step i do i step into an error, i'm sorry but  the usage documentation is unclear.

I'm using Angular version 17, unfortunately i can't use fs (file system) because Angular applications typically run in the browser environment, and the fs module (file system) is a Node.js module for interacting with the file system, which isn't accessible directly in the browser so i used Buffer.

My scenario is like the following..

1) loading the pdf as Uint8Array
2) fetch the p12 file as ArrayBuffer
3) create a signature filed in the pdf.

My code:


    PDFViewerApplication.pdfDocument.getData().then(async (pdfData: Uint8Array) => {

      fetch('assets/AccuSign.p12')
        .then(response => response.arrayBuffer())
        .then(async (data: ArrayBuffer) => {

          const settings = {
            rangePlaceHolder: 9999,
            signatureComputer: <P12SignatureComputerSettings>{
              certificate: Buffer.from(data),
              password: '1q2w3e'
            },
            signatureLength: data.byteLength,
          };

          const pdfSigner = new PdfDigitalSigner(settings);
          await pdfSigner.addFieldAsync(Buffer.from(pdfData), {
            pageNumber: 1,
            rectangle: {
              left: 50,
              top: 641,
              right: 264,
              bottom: 711
            },
            name: 'Faris signature'
          })
          this.downloadPDF(Buffer.from(pdfData))
        })

    });

Then i get two different errors in a random way..

First error:  Too few bytes to read ASN.1 value.

Second error: Buffer is not defined.

I really need help here... i'm stuck with every thing i don't know if the error from the file reading technique or there is steps i need to stick with to accomplish the task

**Comment by remdra** [comment]
You trying to use it in an Angular app (browser side). The library was never tested in browser. It was designed to be used on server side, inside a nodejs app.

An online usage of it can be found on: https://semnezonline.ro. For signing, the pdf is sent to the server and the signed version is returned.

I do not recommand to download the certificate in browser, this has a lot of security risks.

In case you still want to use the lib inside the drowser, let me know and maybe I'll find a solution.

**Comment by remdra** [comment]
How do you want to use the library? Do you want to add a digital signature? Do you want to add only a visual signature (usually a picture)?

Dou want the functionality from https://semnezonline.ro/sign-visual? Or the one from https://semnezonline.ro/sign-digital?

**Comment by farisshomali** [comment]
Thanks for the fast replay i really appreciate that..

I would like to accomplish the visual signing but i thought it would generate a Signature form filed that i could append the drawn signature inside it, i don't know if that possible and yes i need to use it inside the browser

**Comment by farisshomali** [comment]
Ok planes changed, We decided to bake the signature in server side but we noticed that after appending the signature (Visual or Digital), any PDF viewer (PSPDF for example) does not recognize the signature as Sig form field.

Here is a screenshot describing what i mean...

![Screen Shot 2024-04-24 at 2 04 53 PM](https://github.com/remdra/sign-pdf-lib/assets/61110881/542d6cdd-82f9-4a47-b235-eda4da8265a0)

The blue rectangle is a signature form filed created by the pdf viewer and the signature in the footer is signed visually by the link you provided.

I assume the signature in the footer should be existed inside a Sig form field.

Is this achievable ?

**Comment by remdra** [comment]
The site appends a new signature, does not look for an existing field. I think that you want to achieve is

const fieldName = (await pdfSigner.getFieldsAsync(pdf ))[0].name;


const fieldInfo = {
      fieldName: fieldName,

      signature: {
        name: "Test Signer",
        location: "Timisoara",
        reason: "Signing",
        date: new Date(2023, 1, 20, 18, 47, 35),
        contactInfo: "signer@semnezonline.ro",
      },
      visual: {
        background: pdfDigitalSignerAssets.signatureImage,
        texts: [
          {
            lines: ["JOHN", "DOE"],
          },
          {
            lines: [
              "Digitally signed by",
              "JOHN DOE",
              "Date: 2023.11.03",
              "20:28:46 +02'00'",
            ],
          },
        ],
      },
    };
 const fieldSignedPdf = await pdfSigner.signFieldAsync(pdf,  fieldInfo );


see more examples in https://github.com/remdra/sign-pdf-lib/blob/master/src/signer/pdf-digital-signer.spec.ts

The code is not checked, there are just some pieces of code from that file.

If still no result, just attach the file you want to sign and I'll provide the code to sign it.

**Comment by farisshomali** [comment]
Hi, every thing went fine but there is a few cases not working.

1) throw new errors_1.AlreadySignedError(name);

   AlreadySignedError: Signature 'Signature filed 0.13017069274596693' already signed.
   
   The signature field was created using this library using this code:

       const settings = {
              signatureLength: 5000,
               rangePlaceHolder: 99999,
              signatureComputer: {
              certificate: certificateBuffer,
               password: '1q2w3e'
                  }
             }
            const pdfSignatureField = new PdfDigitalSigner(settings);

            const placeholderPdf = await pdfSignatureField.addPlaceholderAsync(pdfBuffer, {

            visual: {
               rectangle: {
               left: 50,
               top: 641,
               right: 264,
                bottom: 711
                },
             },
              pageNumber: 2,
             name: `Signature filed ${Math.random()}`
                }
             )
             
            
             

 Here is how i signed the document:

 
const settings = {
    signatureLength: 4096,
    rangePlaceHolder: 99999,
    signatureComputer: {
      certificate: certificateBuffer,
      password: '1q2w3e'
    }
  };

  const pdfSigner = new PdfDigitalSigner(settings);
  const fieldInfo = {
    fieldName: "Signature filed 0.13017069274596693",
    background: await fs.readFileSync('my_sign.png'),
    signature: {
      name: "Faris Shomali",
      location: "Jordan",
      reason: "Signing",
      date: new Date(datetime.getFullYear(), datetime.getMonth(), datetime.getDate()),
      contactInfo: "f.shomali@accusolution.com",
    }
};

const fieldSignedPdf = await pdfSigner.signFieldAsync(pdfBuffer, fieldInfo);

and here is the file..
[no_background.pdf](https://github.com/remdra/sign-pdf-lib/files/15108936/no_background.pdf)

**Comment by remdra** [comment]
You are almost there... 

Instead 
     const placeholderPdf = await pdfSignatureField.addPlaceholderAsync(pdfBuffer, ....
use 
     const fieldPdf = await pdfSignatureField.addFieldAsync(pdfBuffer, ....

**Comment by farisshomali** [comment]
@remdra Thank you so much! 

I appreciate your help and your quick response
