### ISSUE TITLE
How to translate user click position to signature field rectangle ?

### ISSUE THREAD

**Issue by farisshomali** [remdra/sign-pdf-lib#6]
Assume we need to append a signature field to pdf page based on user selection note that width and height of the field will be fixed.

is it possible ?

**Comment by remdra** [comment]
You can specify the field position;
const parameters: AddFieldParameters = {
    pageNumber: 1,

    rectangle: {
        left: 50,
        top: 641,
        right: 264,
        bottom: 711
    }
};

Is this the answer you are looking for?

**Comment by farisshomali** [comment]
The rectangle in pdf-js can be represented as [x_1, y_1, x_2, y_2 ] to define the bounds of the signature field.

How to transform the [x_1, y_1, x_2, y_2] formula into left,top,right,bottom?

Note that we can specify the width and height of the field as static values.

**Comment by remdra** [comment]
this is an example that adds 2 fileds: 1 with absolute coordinates and one with relative coordinates:

import * as fse from "fs-extra";
import { PDFDocument } from "pdf-lib-incremental-save";
import {
  AddFieldParameters,
  PdfDigitalSigner,
  SignerSettings,
} from "sign-pdf-lib";

async function runAsync(): Promise<void> {
  const settings: SignerSettings = {
    signatureLength: 4096,
    rangePlaceHolder: 9999,

    signatureComputer: {
      certificate: await fse.readFile("certificate.p12"),
      password: "password",
    },
  };
  const pdfSigner = new PdfDigitalSigner(settings);

  const pdf = await fse.readFile("document.pdf");
  const pdfDoc = await PDFDocument.load(pdf);
  const width = pdfDoc.getPage(0).getWidth();
  const height = pdfDoc.getPage(0).getHeight();

  const parameters: AddFieldParameters = {
    pageNumber: 1,

    rectangle: {
      left: 50,
      top: height - 200,
      right: width - 50,
      bottom: height - 200 + 70,
    },
  };
  let fieldPdf = await pdfSigner.addFieldAsync(pdf, parameters);

  const parameters2: AddFieldParameters = {
    pageNumber: 1,

    rectangle: {
      left: 50,
      top: -300,
      right: -50,
      bottom: -300 + 70,
    },
  };
  fieldPdf = await pdfSigner.addFieldAsync(fieldPdf, parameters2);

  await fse.writeFile("fields.pdf", fieldPdf);
}

runAsync();
